name: gestureappflutter
description: Dado virtuale controllato con gesture shake.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true